# GET http://localhost:8080/preferences
# ###
# GET http://localhost:8080/parents
# ###

# POST http://localhost:8080/parents/84/add-child
# content-type: application/json

# {
#     "firstName": "d",
#     "lastName": "br",
#     "age": "12"
# }


# DELETE http://localhost:8080/parents/84/delete-child
# content-type: application/json

# {
#     "firstName": "d",
#     "lastName": "br",
#     "age": "12"
# }

# GET http://localhost:8080/ingredients
# ###
# DELETE  http://localhost:8080/children/85/delete-allergy
# content-type: application/json

# {
#     "allergy": "Eggs"
# }

# POST http://localhost:8080/children/85/add-allergy
# content-type: application/json

# {
#     "allergy": "Fish"
# }

# GET http://localhost:8080/allergies
# ###
# GET http://localhost:8080/children
# ###
# GET http://localhost:8080/foodCategories
# ###
# DELETE http://localhost:8080/children/85/delete-preference
# content-type: application/json

# {
#     "preference": "Lamb" 
# }


# POST http://localhost:8080/children/85/add-preference
# content-type: application/json

# {
#     "preference": "Lamb"
# }



# DELETE http://localhost:8080/parents/84/delete-ingredient
# content-type: application/json

# {
#     "ingredient": "Beef"  
# }

# POST http://localhost:8080/parents/84/add-ingredient
# content-type: application/json

# {
#     "ingredient": "Beef"  
# }




